name: Build Latest

on: [push,workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '8.0.*'

jobs:

  build-win-x64-arm64:
    
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true

      - run: dotnet publish BBDown -r win-x64 -c Release -o artifact-x64
      - run: dotnet publish BBDown -r win-arm64 -c Release -o artifact-arm64

      - name: Upload Artifact[win-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_win-x64
          path: artifact-x64\BBDown.exe

      - name: Upload Artifact[win-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_win-arm64
          path: artifact-arm64\BBDown.exe
  

  build-linux-x64:
    
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    
    steps:
      
      - run: apt-get update
      - run: apt-get install -y curl wget
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: apt-get install -y libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev
      - run: dotnet publish BBDown -r linux-x64 -c Release -o artifact
      
      - name: Upload Artifact[linux-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-x64
          path: artifact/BBDown

  build-linux-musl-x64:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0-preview-alpine

    steps:
      - uses: actions/checkout@v2
      - run: apk update
      - run: | 
          wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
          wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-2.35-r1.apk
          apk add glibc-2.35-r1.apk
      - run: apk --no-cache add clang clang-dev musl-dev git gcc krb5-dev zlib-dev elfutils-dev lldb binutils build-base zlib-static protobuf-dev grpc-plugins grpc-dev
      - run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v24.0/protoc-24.0-linux-x86_64.zip && unzip protoc-24.0-linux-x86_64.zip -d proto_tmp && cp proto_tmp/bin/protoc /usr/bin/ && chmod +x /usr/bin/protoc && rm -rf protoc-24.0-linux-x86_64.zip proto_tmp
      - run: dotnet publish BBDown -r linux-musl-x64 -c Release -o artifact
        env:
          PROTOBUF_PROTOC: /usr/bin/protoc
          GRPC_PROTOC_PLUGIN: /usr/bin/grpc_csharp_plugin
      - run: strip artifact/BBDown
      - name: Upload Artifact[linux-musl-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-musl-x64
          path: artifact/BBDown

  build-linux-arm64:
    
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm64-20220312201346-b2c2436
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r linux-arm64 -c Release -p:StripSymbols=true -p:CppCompilerAndLinker=clang-9 -p:SysRoot=/crossrootfs/arm64 -o artifact
      
      - name: Upload Artifact[linux-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-arm64
          path: artifact/BBDown
          
  build-mac-x64-arm64:
    
    runs-on: macOS-latest
    
    steps:
      
      - uses: actions/checkout@v2
      
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r osx-arm64 -c Release -o artifact-arm64
      - run: dotnet publish BBDown -r osx-x64 -c Release -o artifact-x64

      
      - name: Upload Artifact[osx-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_osx-x64
          path: artifact-x64/BBDown
          
      - name: Upload Artifact[osx-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_osx-arm64
          path: artifact-arm64/BBDown
